#pragma once 
#include <glad/glad.h>
#include <GLFW/glfw3.h>
#include <iostream>
#include "window.h"
#include "shader.h"
#include "mesh.h"
#include "light.h"
#include "bezierCurve.h"
#include "normalMesh.h"
#include "bezierSurface.h"
#include "surfaceMesh.h"
#include "camera.h"
#include <chrono>
#include <thread>
#include <fstream>
#include <sstream>
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>

