#pragma once 
#include <glad/glad.h>
#include <GLFW/glfw3.h>
#include <iostream>
#include "window.h"
#include "shader.h"
#include "mesh.h"
#include <chrono>
#include <thread>
#include <fstream>
#include <sstream>